const DEFAULT_VALUES = {
	SESSION: 25,
	BREAK: 5,
	TIMER_DURATION: 1000,
	MAX_HOLD_DURATION: 1000,
	MIN_HOLD_DURATION: 100
};

const DURATION_RANGE = {
	MIN: 1,
	MAX: 60
};

const TIMER_STATE = {
	PLAYING: 0,
	PAUSED: 1,
	RESET: 2,
	WAITING: 3
};

export { DEFAULT_VALUES, DURATION_RANGE, TIMER_STATE };